/*Tabla Empleados*/
select Email, Pass  from Empleados where Email = '' and Pass = '';
insert into Empleados (Nombre, Apellido, Email, Pass)
values ('David', 'Arias', 'darias@ihersa.com', 'ih258935'),
			('Rosselin', 'Arias', 'ihersa@cwpanama.net', 'ih48234k'),
            ('Sofía', 'Arias', 'sarias@ihersa.com', 'Sofia123!'),
            ('Julio', 'Sam', 'juliosam@ihersa.com', 'jSam5450?'),
            ('Juan', 'Jaen', 'juanjaen@ihersa.com', 'juanJaen8090!');

/*Tabla Empresas*/
select * from Empresas;
INSERT INTO Empresas(Nombre, Tipo) VALUES
 ('AC1 Supply',NULL)
,('Aceros Gamboa','Hojalateria')
,('Aceros Roag','Industria')
,('Aceti Oxigeno','Industria')
,('Agropecuaria El Buen Pastor',NULL)
,('Airpanama','Linea Aerea')
,('Almacen Profelec',NULL)
,('Alpan',NULL)
,('Alstom Panama',NULL)
,('App Plus',NULL)
,('Argos',NULL)
,('Auto Servicio Chu',NULL)
,('Autostar','Automotriz')
,('Azucarera Santa Rosa','Alimentos')
,('Baterias Nacionales',NULL)
,('Bauer',NULL)
,('Bering Motors',NULL)
,('Bimbo De Panama',NULL)
,('Blk Panama',NULL)
,('Blu Logistic',NULL)
,('Budget Rent A Car',NULL)
,('Cable Onda',NULL)
,('Café Duran',NULL)
,('Caisa, S.A.','Alimentos')
,('Calesa',NULL)
,('Cangas Truck','Industria')
,('Carnes Cocle',NULL)
,('Carrocerias Act',NULL)
,('Carrocerias Salazar','Carrocerias')
,('Cartonera Colon',NULL)
,('Casa De La Carne',NULL)
,('Casa De Las Baterias',NULL)
,('Casa De Materiales',NULL)
,('Casa Egeo',NULL)
,('Cedauto',NULL)
,('Cehelsa',NULL)
,('Cementos Chagres','Cementera')
,('Cerveceria Baru',NULL)
,('Cervecerìa Nacional',NULL)
,('China Chech','Construccion')
,('Cindù - Grupo Aeropuerto',NULL)
,('Citas Corozal Visitas',NULL)
,('Coamco','Equipos Alquiler')
,('Cobra',NULL)
,('Cochez',NULL)
,('Coipsa',NULL)
,('Comercial De Motores',NULL)
,('Concretos Del Pacifico',NULL)
,('Consihsa (Cont. Isis Herrera, S.a.)','Construccion')
,('Consorcio Loma Cova',NULL)
,('Consultenos',NULL)
,('Copa',NULL)
,('Copama Cho',NULL)
,('Copama Tm',NULL)
,('Copama Vl',NULL)
,('Copper Group',NULL)
,('Correagua','Metalurgica')
,('Cuarto Frio',NULL)
,('Cusa',NULL)
,('Dac Transport',NULL)
,('Del Monte',NULL)
,('Dicarina',NULL)
,('Discovery Center',NULL)
,('Disur',NULL)
,('Divisiones Finas Sanitarias De Panama, S.A.','Construccion')
,('Doit',NULL)
,('Dollar Rent A Car',NULL)
,('Elevadores Otis','Servicios Elevadores')
,('Eleveitor Grup Panamá','Servicios Elevadores')
,('Empaques De Colon',NULL)
,('Ensa',NULL)
,('Equibal',NULL)
,('Equipos Y Taller Caldito',NULL)
,('Espacios Publicos',NULL)
,('Estrella Azul',NULL)
,('Farkam',NULL)
,('Farmacias Arrocha',NULL)
,('Fausto Salazar',NULL)
,('Fcc','Construccion')
,('Felipe Rodriguez',NULL)
,('Femsa',NULL)
,('Ferreteria Alfa Y Omega',NULL)
,('Ferreteria Martin',NULL)
,('Ficaza',NULL)
,('Fire Protection',NULL)
,('First Quantum',NULL)
,('Formetal',NULL)
,('Fortunato Mangravita',NULL)
,('Gago',NULL)
,('GD Energy Services',NULL)
,('Gedecar',NULL)
,('GEMCO Panama',NULL)
,('Generadora Del Atlantico',NULL)
,('Genius',NULL)
,('GMG Panama',NULL)
,('Golstard','Servicio')
,('Grupo Aluman',NULL)
,('Grupo Alzu',NULL)
,('Grupo Caiza',NULL)
,('Grupo Calesa','Alimentos')
,('Grupo Cegraco','Alimentos')
,('Grupo Cirsa',NULL)
,('Grupo Cocige',NULL)
,('Grupo Kame',NULL)
,('Grupo Melo',NULL)
,('Grupo Nova',NULL)
,('Grupo Patiño',NULL)
,('Grupo Rey',NULL)
,('Grupo Rgj',NULL)
,('Grupo Tiesa',NULL)
,('Grupo Tova',NULL)
,('Grupo Vargas Matamoros',NULL)
,('Gt Truck Services, S.A.','Logistica')
,('Hojalateria Marinmar',NULL)
,('Hojalateria Semag',NULL)
,('Hopsa',NULL)
,('Hormigon Express',NULL)
,('Hunter Douglas',NULL)
,('Imarsol',NULL)
,('Impacolsa',NULL)
,('Importadora Farkam',NULL)
,('Importadora Maduro',NULL)
,('Inbobe Panama',NULL)
,('Industrias Cattan',NULL)
,('Industrias Correagua',NULL)
,('Industrias Galaxia',NULL)
,('Industrias Metalicas Carmona','Industria')
,('Inelma',NULL)
,('Ingenio Santa Rosa',NULL)
,('Inproser',NULL)
,('Intaco',NULL)
,('Interglass',NULL)
,('ISA',NULL)
,('Jan De Nul',NULL)
,('Jhon Deere',NULL)
,('La Regional De Seguros',NULL)
,('Laboratorio Turbo Inyeccion Victor',NULL)
,('Larrinaga, S.A.','Logistica')
,('Leños Y Carbon',NULL)
,('Levapan',NULL)
,('Lieberhh',NULL)
,('Linea 2',NULL)
,('Macello',NULL)
,('Maribel','Industria')
,('Marine Supply',NULL)
,('Materiales JC',NULL)
,('Max E. Jimenez',NULL)
,('Mecanica Riva, S.A.','Industria')
,('Mecanizados De Precision',NULL)
,('Meco','Construccion')
,('Mega Montajes',NULL)
,('Mega Servicios Y Alquielers',NULL)
,('Mercansa',NULL)
,('Metales 24','Metales')
,('Mi Bus',NULL)
,('Minera Panama',NULL)
,('Montana',NULL)
,('Mtp Corp',NULL)
,('Multicomercial',NULL)
,('Naas Panama',NULL)
,('National Rent A Car',NULL)
,('Nestle',NULL)
,('Nestle Panama',NULL)
,('Ocean Polution',NULL)
,('Onddi',NULL)
,('Panam Generating Ltd',NULL)
,('Panama Canal Railway',NULL)
,('Panama Ports',NULL)
,('Panamotors',NULL)
,('Panatruck',NULL)
,('Papeleria Istmeña',NULL)
,('Pasa - Puente Atlántico',NULL)
,('Pazko',NULL)
,('Petroautos',NULL)
,('Plastifom',NULL)
,('Plofelec',NULL)
,('Powergen','Equipos Alquiler')
,('Prcesmart','Alimentos')
,('Pretel',NULL)
,('Pricesmart',NULL)
,('Productos Alimenticios Pascual',NULL)
,('Raemco','Ferreteria')
,('Raenco',NULL)
,('Renovación Colon',NULL)
,('Renta Equipos','Alquiler De Equipos')
,('Ricardo Perez',NULL)
,('Rodelag',NULL)
,('Saam Smith Towage',NULL)
,('Salvamart',NULL)
,('Servicarnes',NULL)
,('Servicios Electricos',NULL)
,('Sika Panama',NULL)
,('Sofratesa',NULL)
,('Super Carnes',NULL)
,('Super Centro El Tajonaso',NULL)
,('Super Materiales',NULL)
,('Suplidores Barcos',NULL)
,('Tagaropolus',NULL)
,('Taller Alfredo',NULL)
,('Talleres Industriales',NULL)
,('Tandor',NULL)
,('Tesa',NULL)
,('Thyssenkrupp','Servicio')
,('Tiesa','Carrocerias')
,('Torneria Tecmec',NULL)
,('Tornillos Y Herramientas Yasiel',NULL)
,('Trebol',NULL)
,('Tropigas',NULL)
,('Tso-cim',NULL)
,('Tu Cocina',NULL)
,('Tubotec',NULL)
,('Tucan Real State',NULL)
,('Tuñon Garcia','Carrocerias')
,('Varela Hnos - Compañia Panameña De Licores',NULL)
,('Vargas Matamoros','Automotriz')
,('Viveres Panama (Riba)',NULL)
,('Weldon',NULL);

select * from Empresas;